const skillsList = [
    "JavaScript",
    "ReactJS",
    "Node.js",
    "Python",
    "HTML",
    "CSS",
    "Java",
    "C++",
    "Angular",
    "Vue.js",
    "Django",
    "Express.js",
    "MongoDB",
    "SQL",
    "Git",
    "Redux",
    "TypeScript",
    "Bootstrap",
    "Sass",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "C#",
    "ASP.NET",
    "RESTful API Design",
    "GraphQL",
    "WebSocket",
    "Microservices",
    "Progressive Web Apps (PWAs)",
    "Responsive Web Design",
    "Jest",
    "Mocha",
    "Selenium",
    "JUnit",
    "NUnit",
    "Webpack",
    "Babel",
    "ESLint",
    "Prettier",
    "Amazon Web Services (AWS)",
    "Microsoft Azure",
    "Google Cloud Platform (GCP)",
    "Heroku",
    "DigitalOcean",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "Travis CI",
    "CircleCI",
    "Continuous Integration",
    "Continuous Deployment",
    "Agile Development",
    "Scrum",
    "Kanban",
    "Firebase",
    "OAuth",
    "JSON Web Tokens (JWT)",
    "GraphQL",
    "Postman",
    "Swagger",
    "Nginx",
    "Apache",
    "Linux",
    "Shell Scripting",
    "Bash",
    "GitLab",
    "Bitbucket",
    "Jira",
    "Confluence",
    "Trello",
    "Slack",
    "MERN Stack",
    "MEAN Stack",
    "LAMP Stack",
    ".NET Core",
    "Rust",
    "Go",
    "VueX",
    "RxJS",
    "TensorFlow",
    "PyTorch",
    "Machine Learning",
    "Artificial Intelligence",
    "Blockchain",
    "Ethereum",
    "Smart Contracts",
    "WebAssembly (Wasm)",
    "Raspberry Pi",
    "Arduino",
    "UI/UX Design",
    "Figma",
    "Adobe Creative Suite",
    "Accessibility",
    "Performance Optimization",
    "Security",
  ];
  
  export default skillsList;
   